[project]
name = "pc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "firebase-admin>=6.9.0",
    "flask>=3.1.1",
    "fpdf>=1.7.2",
    "matplotlib>=3.10.3",
    "seaborn>=0.13.2",
]
